security:
    password_hashers:
        App\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /
            logout: ~

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS  }
        - { path: ^/users, roles: PUBLIC_ACCESS  }
        - { path: ^/, roles: ROLE_USER }
